dependencies:
  - name: postgresql
    version: 10.9.4
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    condition: postgresql.installdep.enable

  - name: rabbitmq
    version: 7.5.6
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    condition: rabbitmq.installdep.enable

  - name: elasticsearch
    version: 7.10.2
    repository: https://helm.elastic.co
    condition: elasticsearch.installdep.enable

  - name: minio
    version: 7.1.9
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    condition: minio.installdep.enable
